config/routes.rb
Rails.application.routes.draw do
  get 'post/create'
  get 'post/store'
  get 'post/list'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'homes/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#index"
 #  Rails.application.routes.draw do
  get 'post/create'
  post 'post/store'
  get 'post/list'
  get 'post/delete/:id(.:format)', :to => 'post#destroy'
  get 'post/edit/:id(.:format)', :to => 'post#edit'
  post 'post/update/:id(.:format)', :to => 'post#update'
  post 'post_comment/:id(.:format)', :to => 'post#comment_create'
  post 'comment_edit/:id(.:format)', :to => 'post#comment_update'
  get 'comment_delete/:id(.:format)', :to => 'post#comment_delete'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # get 'homes/index'
	#   devise_for :user
	# end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
	  post_list_path
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def create
  end

  def store
  	auth = {
		  cloud_name: ENV["cloud_name"],
		  api_key:    ENV["api_key"],
		  api_secret: ENV["api_secret"]
		}

  	@image = Cloudinary::Uploader.upload(params[:media], auth) if params[:media].present?
  	url = @image['secure_url'] if @image.present?
    # create a new post object and save to db
    @post = current_user.posts.new({:title => params[:title], :body => params[:body], :author => params[:author],  :media => url})
    @post.save
    # trigger an event with pusher
    redirect_to(post_list_path)
  end

  def list
  	if current_user.superadmin_role? 
  		@posts = Post.all.order("created_at DESC")
		elsif current_user.user_role? 
			@posts = current_user.posts.order("created_at DESC")
		end 
  end

 	def destroy
 		post = Post.find(params[:id]) rescue nil
 		post.destroy if post.present?
 		redirect_to(post_list_path)
 	end

 	def edit
 		@post = Post.find(params[:id]) rescue nil
 	end

 	def update
 		@post = Post.find(params[:id]) rescue nil
 
 		if @post.present?
 			@post.update({:title => params[:title], :body => params[:body], :author => params[:author]})
 		end
 		redirect_to(post_list_path)
 	end

 	def comment_create
 		@post = Post.find(params[:id]) rescue nil
 		if @post.present?
 			@post.comments.create(comment_text: params[:comment_text])
 		end
 		redirect_to(post_list_path)
 	end

 	def comment_update
 		comment = Comment.find(params[:id]) rescue nil
 		comment.update(comment_text: params[:comment_text]) if comment.present?
 		redirect_to(post_list_path)
 	end

 	def comment_delete
 		comment = Comment.find(params[:id]) rescue nil
 		comment.destroy if comment.present?
 		redirect_to(post_list_path)
 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/homes/index.html.erb
<% if current_user.nil? %>
	<%= link_to new_user_session_path, class: 'login-button' do %>Sign in<% end %>
	<%= link_to new_user_registration_path, class: 'login-button' do %>Sign up<% end %>
<% else %>
	<!-- <%#= link_to app_dashboard_index_path, class: 'login-button' do %>Go to App<%# end %> -->
	<% if current_user.superadmin_role? %>
		<p>Visible only for superadmins and supervisors! </p>
	<% elsif current_user.user_role? %>
		<p>Visible only for users! </p>
	<% end %>
	<%= link_to destroy_user_session_path, method: :delete do %>Log out<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/post/_post_form.html.erb
<div class="form-group">
  <label for="title">Title</label>
  <input type="text" name="title" class="form-control" value="<%= @post.title if @post.present? %>">
</div>
<% unless @post && @post.media %>
  <div class="form-group">
    <label for="media">Post Media</label>
    <input type="file" name="media" class="form-control media-upload" value="<%= @post.title if @post.present? %>">
  </div>
<% end %>
<div class="form-group">
  <label for="author">Post Author</label>
  <input type="text" name="author" class="form-control" value="<%= @post.author if @post.present? %>"/>
</div>
<div class="form-group">
  <label for="body">Post Content</label>
  <textarea name="body" class="form-control" cols="30" rows="10"><%= @post.body if @post.present? %></textarea>
</div>
<div class="from-group">
  <div><input type="submit" value="Create Post"></div>
</div>

app/views/post/create.html.erb
<div class="title">
  <h1>Live Blog</h1>
  <p>Editor View</p>
</div>
<div style="text-align:center">
  <p><strong>Fill and submit the form below to create a new post</strong></p>
  <form method="POST" action="/post/store" enctype="multipart/form-data" class="post-form">
    <%= token_tag %>
 	<%= render 'post_form' %>
  </form>
</div>

app/views/post/edit.html.erb
<div class="title">
  <h1>Live Blog</h1>
  <p>Editor View</p>
</div>
<div style="text-align:center">
  <p><strong>Fill and submit the form below to create a new post</strong></p>
  <form method="POST" action="/post/update/<%= @post.id %>" enctype="multipart/form-data" class="post-form">
    <%= token_tag %>
 	<%= render 'post_form', post: @post %>
  </form>
</div>

app/views/post/list.html.erb
<!-- app/views/home/index.html.erb -->
<%= link_to destroy_user_session_path, method: :delete do %>Log out<% end %>
<div class="wrapper">
  <div class="title">
    <h1>Live blog with Ruby</h1>
    <p>New posts will be displayed in realtime</p>
  </div>
  <div class="posts" id="post_section">
  	<a href="<%= post_create_path %>">Create post</a>
    <% @posts.each do |post| %>
	    <div class="post-card">
	      <a href="/post/delete/<%= post.id %>">Delete</a>
	      <a href="/post/edit/<%= post.id %>">Edit</a>
	      <img class="image" src="<%= post.media %>">
	      <div class="title">
	        <h2>
	          <%= post.title %>
	        </h2>
	      </div>
	      <div class="body-trunc">
	        <p>
	          <%= post.body %>
	        </p>
	      </div>
	      <hr>
	      <form method="POST" action="/post_comment/<%= post.id %>" class="post-form">
				  <%= token_tag %>
				 	<input type="text" name="comment_text">
				 	<button type="submit">post</button>
				</form>
	      <% if post.comments.present? %>
		      <% post.comments.each do |comment| %>
		      	<form method="POST" action="/comment_edit/<%= comment.id %>" class="post-form">
		      		<%= token_tag %>
		      		<input type="text" name="comment_text" value="<%= comment.comment_text %>">
		      		<button type="submit">edit</button>
		      		<a href="/comment_delete/<%= comment.id %>">delete</a>
		      	</form>
		      	<br>
		      <% end %>
		  	<% end %>
	    </div>
    <% end %>
  </div>
</div>

app/views/post/store.html.erb
<h1>Post#store</h1>
<p>Find me in app/views/post/store.html.erb</p>